steps:
  mtaBuild:
    platform: 'CF'
  cloudFoundryDeploy:
    cloudFoundry:
      apiEndpoint: 'https://api.cf.us10.hana.ondemand.com' # default: 'https://api.cf.eu10.hana.ondemand.com'
      org: '3e2d8d81-f839-432f-9b1a-1ea25a3111cf'
      space: 'dev'
      credentialsId: 'CF_CREDENTIALSID'
